regions:
    austin:
        name: Austin
        state: Texas
        counties:
        - Bastrop
        - Caldwell
        - Hays
        - Travis
        - Williamson
        bbox:
        - -98.2976
        - 29.630718
        - -97.024461
        - 30.904414
    baton_rouge:
        name: Baton Rouge
        state: Louisiana
        counties:
        - Ascension
        - East Baton Rouge
        - East Feliciana
        - Iberville
        - Livingston
        - Pointe Coupee
        - St. Helena
        - West Baton Rouge
        - West Feliciana
        bbox:
        - -91.823072
        - 30.02556
        - -90.47368
        - 31.044794
    houston:
        name: Houston
        state: Texas
        counties:
        - Austin
        - Brazoria
        - Chambers
        - Fort Bend
        - Galveston
        - Harris
        - Liberty
        - Montgomery
        - Waller
        bbox:
        - -96.62198
        - 28.764837
        - -94.353383
        - 30.630284
    indianapolis:
        name: Indianapolis
        state: Indiana
        counties:
        - Boone
        - Brown
        - Hamilton
        - Hancock
        - Hendricks
        - Johnson
        - Madison
        - Marion
        - Morgan
        - Putnam
        - Shelby
        bbox:
        - -87.014727
        - 39.048357
        - -85.575541
        - 40.379799
    san_antonio:
        name: San Antonio
        state: Texas
        counties:
        - Atascosa
        - Bandera
        - Bexar
        - Comal
        - Guadalupe
        - Kendall
        - Medina
        - Wilson
        bbox:
        - -99.603323
        - 28.612658
        - -97.630985
        - 30.138954
datasets:
    D1:
        region: baton_rouge
        start: '2021-08-01'
        end: '2021-08-25'
    D2:
        region: baton_rouge
        start: '2021-08-26'
        end: '2021-09-07'
    D3:
        region: baton_rouge
        start: '2021-09-08'
        end: '2021-11-30'
    D4:
        region: indianapolis
        start: '2020-03-01'
        end: '2020-03-15'
    D5:
        region: indianapolis
        start: '2020-03-16'
        end: '2020-03-31'
    D6:
        region: indianapolis
        start: '2020-03-01'
        end: '2020-03-31'
    D7:
        region: austin
        start: '2021-07-01'
        end: '2021-07-07'
    D8:
        region: houston
        start: '2021-07-01'
        end: '2021-07-07'
filters:
    all_pings:
        max_gps_error (m): 50
        max_speed (m/s): 50
        max_acceleration (m/s2): 10
        max_deceleration (m/s2): 10
    base_day_hours:
    - 7
    - 19
    min_total_nightly_pts: 10
    slot_size: 1800
algorithms:
    meanshift:
        radius: 250
        bin_seeding: true
        min_bin_freq: 2
        max_iter: 50
    superping:
        slot_size: 1800
    grid_frequency:
        cell_size: 20
    A0:
        name: Centroid method
        color: '#10ae01'
        marker: .
    A1:
        name: All-time clustering method
        color: '#047cbd'
        marker: v
    A2:
        name: Binned clustering method
        color: '#4930c7'
        marker: ^
    A3:
        name: Stay-point method
        color: '#ff7e81'
        marker: '*'
    A4:
        name: Grid frequency method
        color: '#c92ad5'
        marker: d
